version: "2.1"

volumes:
  ha_config:
  mqtt:
  octoprint:

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ha_config:/config
    labels:
      io.balena.features.dbus: "1"
    ports:
      - 8123:8123
    environment:
      TZ: Europe/London
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    restart: unless-stopped
    privileged: true
    network_mode: host
  mqtt:
    build: mqtt
    ports:
      - 1883:1883
    volumes:
      - mqtt:/mosquitto/data
    tmpfs:
      - /mosquitto/log
    restart: unless-stopped
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 3006:80
    privileged: true
    volumes:
      - octoprint:/octoprint
      - /dev:/dev
  # TTS for Home Assistant
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=en_US-lessac-medium
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
    volumes:
      - /path/to/piper/data:/config
    ports:
      - 10200:10200
    restart: unless-stopped